[package]
name = "glium-experiments"
version = "0.1.0"
authors = ["Kolja Blauhut <koljablauhut@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"